# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'totals.ui'
#
# Created: Sat Nov 05 19:07:46 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TotalsWidget(object):
    def setupUi(self, TotalsWidget):
        TotalsWidget.setObjectName(_fromUtf8("TotalsWidget"))
        TotalsWidget.resize(300, 339)
        TotalsWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        TotalsWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_minLoad = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_minLoad.sizePolicy().hasHeightForWidth())
        self.lineEdit_minLoad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.lineEdit_minLoad.setFont(font)
        self.lineEdit_minLoad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_minLoad.setReadOnly(True)
        self.lineEdit_minLoad.setObjectName(_fromUtf8("lineEdit_minLoad"))
        self.gridLayout_2.addWidget(self.lineEdit_minLoad, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_avgLoad = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_avgLoad.sizePolicy().hasHeightForWidth())
        self.lineEdit_avgLoad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.lineEdit_avgLoad.setFont(font)
        self.lineEdit_avgLoad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_avgLoad.setReadOnly(True)
        self.lineEdit_avgLoad.setObjectName(_fromUtf8("lineEdit_avgLoad"))
        self.gridLayout_2.addWidget(self.lineEdit_avgLoad, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit_maxLoad = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_maxLoad.sizePolicy().hasHeightForWidth())
        self.lineEdit_maxLoad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.lineEdit_maxLoad.setFont(font)
        self.lineEdit_maxLoad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_maxLoad.setReadOnly(True)
        self.lineEdit_maxLoad.setObjectName(_fromUtf8("lineEdit_maxLoad"))
        self.gridLayout_2.addWidget(self.lineEdit_maxLoad, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_treeNodesCount = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.lineEdit_treeNodesCount.setFont(font)
        self.lineEdit_treeNodesCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_treeNodesCount.setObjectName(_fromUtf8("lineEdit_treeNodesCount"))
        self.gridLayout.addWidget(self.lineEdit_treeNodesCount, 1, 1, 1, 1)
        self.lineEdit_treeLeavesCount = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.lineEdit_treeLeavesCount.setFont(font)
        self.lineEdit_treeLeavesCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_treeLeavesCount.setReadOnly(True)
        self.lineEdit_treeLeavesCount.setObjectName(_fromUtf8("lineEdit_treeLeavesCount"))
        self.gridLayout.addWidget(self.lineEdit_treeLeavesCount, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        TotalsWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(TotalsWidget)
        QtCore.QMetaObject.connectSlotsByName(TotalsWidget)

    def retranslateUi(self, TotalsWidget):
        TotalsWidget.setWindowTitle(QtGui.QApplication.translate("TotalsWidget", "Общие данные", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setToolTip(QtGui.QApplication.translate("TotalsWidget", "Загруженность исполнителей", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("TotalsWidget", "Загруженность", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TotalsWidget", "Миним.:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TotalsWidget", "Средняя:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TotalsWidget", "Максим.:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("TotalsWidget", "Дерево решений", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TotalsWidget", "Общее кол-во узлов:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TotalsWidget", "Кол-во листов:", None, QtGui.QApplication.UnicodeUTF8))

